#! /usr/bin/env python
# -*- coding: utf-8 -*-

u"""
driver script for Fortran2CHeader

:author: `Berthold Hoellmann <hoel@GL-group.com>`__
:newfield project: Project
:project: Fortran2CHeader
:copyright: Copyright (C) 2010 by Germanischer Lloyd AG"""

#  ID: $Id$
__date__      = u"$Date$"[5:-1]
__version__   = "$Revision$"[10:-1]
__docformat__ = "restructuredtext en"

import fortran2cheader
fortran2cheader.main()

# Local Variables:
# mode:python
# mode:flyspell
# compile-command:"python setup.py build"
# End:
